apiVersion: ml.jedimindtricks.example/v1alpha1
kind: ModelDeployment
metadata:
 namespace: default 
 name: sentiment-analyzer
spec:
  live:
    image: k3d-registry.localhost:5000/model-server:latest
    replicas: 2
  shadow:
    image: k3d-registry.localhost:5000/model-server:latest
    replicas: 1
  trafficMirror: true
  rolloutStrategy: rolling
  probes:
    livenessPath: /health
    readinessPath: /ready
  configRef: sentiment-config
